CREATE OR REPLACE TABLE
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_sales_agent_activity_source` AS
SELECT
  MEMBER_KY,
  PAYMENT_DETAIL_KY,
  BRANCH_KY,
  MEMBERSHIP_BRANCH_KY,
  AGENT_ID,
  SALES_AGENT_ACTIVITY_KY,
  TRANSACTION_DT,
  COMMISSION_CD,
  RIDER_COMP_CD,
  EXPIRATION_DT,
  SOLICITATION_CD,
  SOURCE_OF_SALE,
  TRANSACTION_CD,
  DUES_AT,
  CASE when DAILY_BILLED_IND is null then 'U'
  else DAILY_BILLED_IND END DAILY_BILLED_IND ,
  BILLING_CATEGORY_CD,
  BILLING_SUBCAT_CD,
    CASE when COMMISSIONABLE_FL is null then 'U'
  else COMMISSIONABLE_FL END COMMISSIONABLE_FL ,
    CASE when ADD_ON_FL is null then 'U'
  else ADD_ON_FL END ADD_ON_FL ,
  CASE when AUTORENEWAL_FL is null then 'U'
  else AUTORENEWAL_FL END AUTORENEWAL_FL ,
  FEE_TYPE,
  CASE when DONATION_KY is null then 'U'
  WHEN DONATION_KY='1' THEN 'Y'
  else DONATION_KY END DONATION_KY,
  CASE when paymentplan_fl is null then 'U'
  else paymentplan_fl END paymentplan_fl ,
  ZIP,
  DAILY_COUNT,
  CASE when DAILY_COUNT_IND is null then 'U'
  else DAILY_COUNT_IND END DAILY_COUNT_IND ,
  LAST_UPD_DT,
  DATA_SOURCE,
  ROW_NUMBER() OVER(PARTITION BY sales_agent_source.SALES_AGENT_ACTIVITY_KY, sales_agent_source.last_upd_dt, sales_agent_source.data_source ORDER BY NULL) AS dupe_check
FROM (
  SELECT
    MEMBER_KY,
    PAYMENT_DETAIL_KY,
    BRANCH_KY,
    MEMBERSHIP_BRANCH_KY,
    AGENT_ID,
    SALES_AGENT_ACTIVITY_KY,
    TRANSACTION_DT,
    COMMISSION_CD,
    RIDER_COMP_CD,
    EXPIRATION_DT,
    SOLICITATION_CD,
    SOURCE_OF_SALE,
    TRANSACTION_CD,
    DUES_AT,
    DAILY_BILLED_IND,
    BILLING_CATEGORY_CD,
    BILLING_SUBCAT_CD,
    COMMISSIONABLE_FL,
    ADD_ON_FL,
    AUTORENEWAL_FL,
    FEE_TYPE,
    DONATION_KY,
    paymentplan_fl,
    ZIP,
    NULL AS DAILY_COUNT,
    DAILY_COUNT_IND,
    LAST_UPD_DT,
    'SALES_AGENT_ACTIVITY' AS DATA_SOURCE
  FROM
    `{{ var.value.INGESTION_PROJECT }}.mzp.sales_agent_activity`
  UNION ALL
  SELECT
    NULL AS MEMBER_KY,
    NULL AS PAYMENT_DETAIL_KY,
    BRANCH_KY,
    NULL AS MEMBERSHIP_BRANCH_KY,
    NULL AS AGENT_ID,
    DAILY_COUNTS_SUMMARY_KY AS SALES_AGENT_ACTIVITY_KY,
    TRANSACTION_DT,
    COMMISSION_CD,
    RIDER_COMP_CD,
    EXPIRATION_DT,
    SOLICITATION_CD,
    SOURCE_OF_SALE,
    NULL AS TRANSACTION_CD,
    NULL AS DUES_AT,
    NULL AS DAILY_BILLED_IND,
    NULL AS BILLING_CATEGORY_CD,
    MEMBER_TYPE_CD AS BILLING_SUBCAT_CD,
    NULL AS COMMISSIONABLE_FL,
    NULL AS ADD_ON_FL,
    NULL AS AUTORENEWAL_FL,
    NULL AS FEE_TYPE,
    NULL AS DONATION_KY,
    NULL AS paymentplan_fl,
    NULL AS ZIP,
    DAILY_COUNT,
    NULL AS DAILY_COUNT_IND,
    LAST_UPD_DT,
    'DAILY_COUNT_SUMMARY' AS DATA_SOURCE 
  FROM
    `{{ var.value.INGESTION_PROJECT }}.mzp.daily_counts_summary`
) sales_agent_source
