 CREATE OR REPLACE TABLE
    `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_membership_work_stage` AS
  SELECT
    COALESCE(target.mbrs_adw_key,
      GENERATE_UUID()) mbrs_adw_key,
    source.address_adw_key,
    CAST (source.phone_adw_key AS string) phone_adw_key,
    CAST (source.product_adw_key AS string) product_adw_key,
    CAST (source.aca_office_adw_key AS string) aca_office_adw_key,
    CAST (source.mbrs_source_system_key AS int64) mbrs_source_system_key,
    source.mbrs_id ,
    source.mbrs_status_cd,
    source.mbrs_billing_cd,
    CAST(source.mbrs_status_dtm AS datetime) mbrs_status_dtm,
    CAST(substr (source.mbrs_cancel_dt,
        0,
        10) AS date) mbrs_cancel_dt,
    source.mbrs_billing_category_cd,
    CAST(source.mbrs_dues_cost_amt AS numeric) mbrs_dues_cost_amt,
    CAST(source.mbrs_dues_adj_amt AS numeric) mbrs_dues_adj_amt,
    source.mbrs_future_cancel_ind,
    CAST(substr (source.mbrs_future_cancel_dt,
        0,
        10) AS date) mbrs_future_cancel_dt,
    source.mbrs_out_of_territory_cd,
    CAST(source.mbrs_address_change_dtm AS datetime) mbrs_address_change_dtm,
    CAST(source.mbrs_cdx_export_update_dtm AS datetime) mbrs_cdx_export_update_dtm,
    CAST(source.mbrs_tier_key AS float64) mbrs_tier_key,
    source.mbrs_temporary_address_ind,
    source.previous_club_mbrs_id ,
    source.previous_club_cd,
    source.mbrs_transfer_club_cd,
    CAST(source.mbrs_transfer_dtm AS datetime) mbrs_transfer_dtm,
    CAST(source.mbrs_merged_previous_club_cd AS string) mbrs_merged_previous_club_cd,
    CAST(source.mbrs_mbrs_merged_previous_id  AS string) mbrs_mbrs_merged_previous_id ,
    safe_cast(source.mbrs_mbrs_merged_previous_key as int64) as mbrs_mbrs_merged_previous_key,
    source.mbrs_dn_solicit_ind,
    source.mbrs_bad_address_ind,
    source.mbrs_dn_send_pubs_ind,
    source.mbrs_market_tracking_cd,
    source.mbrs_salvage_ind,
    source.mbrs_salvaged_ind,
    source.mbrs_dn_salvage_ind,
    source.mbrs_group_cd,
    source.mbrs_typ_cd,
    source.mbrs_ebill_ind,
    source.mbrs_marketing_segmntn_cd,
    source.mbrs_promo_cd,
    source.mbrs_phone_typ_cd,
    source.mbrs_ers_abuser_ind,
    source.mbrs_shadow_mcycle_ind,
    source.mbrs_student_ind,
    source.mbrs_address_ncoa_update_ind,
    source.mbrs_assigned_retention_ind,
    source.mbrs_mbrs_no_promotion_ind,
    source.mbrs_dn_offer_plus_ind,
    source.mbrs_aaawld_online_ed_ind,
    source.mbrs_shadowrv_coverage_ind,
    source.mbrs_heavy_ers_ind,
    CAST(source.mbrs_purge_ind AS string) mbrs_purge_ind,
    CAST(source.mbrs_unapplied_amt AS numeric) mbrs_unapplied_amt,
    CAST(source.mbrs_advance_payment_amt AS numeric) mbrs_advance_payment_amt,
    0 as mbrs_balance_amt,
    CAST(substr(source.payment_plan_future_cancel_dt, 0, 10) AS date) as payment_plan_future_cancel_dt,
    source.payment_plan_future_cancel_ind as payment_plan_future_cancel_ind,
    source.switch_prim_ind as switch_prim_ind,
    source.supress_bill_ind as supress_bill_ind,
    CAST(substr(source.offer_end_dt, 0, 10) AS date) as offer_end_dt,
    source.old_payment_plan_ind as old_payment_plan_ind,
    CAST(source.carry_over_amt AS numeric) as carry_over_amt,
    last_upd_dt AS effective_start_datetime,
    CAST('9999-12-31' AS datetime) effective_end_datetime,
    'Y' AS actv_ind,
    source.adw_row_hash,
    CURRENT_DATETIME() integrate_insert_datetime,
    {{ dag_run.id }} integrate_insert_batch_number,
    CURRENT_DATETIME() integrate_update_datetime,
    {{ dag_run.id }} integrate_update_batch_number
  FROM
    `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_membership_work_transformed` source
  LEFT JOIN
    `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_membership` target
  ON
    (safe_cast(source.mbrs_source_system_key as int64)=target.mbrs_source_system_key
      AND target.actv_ind='Y')
  WHERE
    target.mbrs_adw_key IS NULL
    OR source.adw_row_hash <> target.adw_row_hash
  UNION ALL
  SELECT
    target.mbrs_adw_key,
    target.address_adw_key,
    target.phone_adw_key,
    target.product_adw_key,
    target.aca_office_adw_key,
    target.mbrs_source_system_key,
    target.mbrs_id ,
    target.mbrs_status_cd,
    target.mbrs_billing_cd,
    target.mbrs_status_dtm,
    target.mbrs_cancel_dt,
    source.mbrs_billing_category_cd,
    target.mbrs_dues_cost_amt,
    target.mbrs_dues_adj_amt,
    target.mbrs_future_cancel_ind,
    target.mbrs_future_cancel_dt,
    target.mbrs_out_of_territory_cd,
    target.mbrs_address_change_dtm,
    target.mbrs_cdx_export_update_dtm,
    target.mbrs_tier_key,
    target.mbrs_temporary_address_ind,
    target.previous_club_mbrs_id ,
    target.previous_club_cd,
    target.mbrs_transfer_club_cd,
    target.mbrs_transfer_dtm,
    target.mbrs_merged_previous_club_cd,
    target.mbrs_mbrs_merged_previous_id ,
    target.mbrs_mbrs_merged_previous_key,
    target.mbrs_dn_solicit_ind,
    target.mbrs_bad_address_ind,
    target.mbrs_dn_send_pubs_ind,
    target.mbrs_market_tracking_cd,
    target.mbrs_salvage_ind,
    target.mbrs_salvaged_ind,
    target.mbrs_dn_salvage_ind,
    target.mbrs_group_cd,
    target.mbrs_typ_cd,
    target.mbrs_ebill_ind,
    target.mbrs_marketing_segmntn_cd,
    target.mbrs_promo_cd,
    target.mbrs_phone_typ_cd,
    target.mbrs_ers_abuser_ind,
    target.mbrs_shadow_mcycle_ind,
    target.mbrs_student_ind,
    target.mbrs_address_ncoa_update_ind,
    target.mbrs_assigned_retention_ind,
    target.mbrs_mbrs_no_promotion_ind,
    target.mbrs_dn_offer_plus_ind,
    target.mbrs_aaawld_online_ed_ind,
    target.mbrs_shadowrv_coverage_ind,
    target.mbrs_heavy_ers_ind,
    target.mbrs_purge_ind,
    target.mbrs_unapplied_amt,
    target.mbrs_advance_payment_amt,
    target.mbrs_balance_amt,
    target.payment_plan_future_cancel_dt,
    target.payment_plan_future_cancel_ind,
    target. switch_prim_ind,
    target.supress_bill_ind,
    target.offer_end_dt,
    target.old_payment_plan_ind,
    target.carry_over_amt,
    target.effective_start_datetime,
    DATETIME_SUB(source.last_upd_dt,
      INTERVAL 1 second) AS effective_end_datetime,
    'N' AS actv_ind,
    target.adw_row_hash,
    target.integrate_insert_datetime,
    target.integrate_insert_batch_number,
    CURRENT_DATETIME(),
    target.integrate_update_batch_number
  FROM
    `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_membership_work_transformed` source
  JOIN
    `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_membership` target
  ON
    (safe_cast(source.mbrs_source_system_key as int64)=target.mbrs_source_system_key
      AND target.actv_ind='Y')
  WHERE
    source.adw_row_hash <> target.adw_row_hash
