CREATE OR REPLACE TABLE
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_payment_summary_source` AS
SELECT
  membership_payment_ky,
  membership_ky,
  payment_dt,
  payment_at,
  batch_name,
  payment_method_cd,
  cc_type_cd,
  cc_expiration_dt,
  transaction_type_cd,
  adjustment_description_cd,
  source_cd,
  create_dt,
  paid_by_cd,
  cc_authorization_nr,
  reason_cd,
  check_nr,
  check_dt,
  rev_membership_payment_ky,
  donor_nr,
  bill_summary_ky,
  pnref,
  user_id,
  unapplied_at,
  parent_payment_ky,
  pos_sale_id,
  pos_ofc_id,
  pos_cust_recpt_nr,
  batch_ky,
  pos_comment,
  pos_consultant_id,
  cc_first_name,
  cc_middle_name,
  cc_last_name,
  cc_street,
  cc_zip,
  ach_bank_name,
  ach_bank_account_type,
  ach_bank_account_name,
  ach_authorization_nr,
  ach_street,
  ach_city,
  ach_state,
  ach_zip,
  ach_email,
  transaction_id,
  cc_transaction_id,
  advance_pay_at,
  ach_token,
  transaction_cd,
  branch_ky,
  cc_last_four,
  cc_state,
  cc_city,
  last_upd_dt,
  adw_lake_insert_datetime,
  adw_lake_insert_batch_number,
  ROW_NUMBER() OVER(PARTITION BY membership_payment_ky ORDER BY last_upd_dt DESC) AS dupe_check
FROM
  `{{ var.value.INGESTION_PROJECT }}.mzp.payment_summary`
WHERE
  CAST(last_upd_dt AS datetime) > (
  SELECT
    MAX(effective_start_datetime)
  FROM
    `{{ var.value.INTEGRATION_PROJECT }}.adw.mbrs_payment_applied_summary`)