jar_files: gs://adw_admin_db_connections/ingestion_jars/sqoop-1.4.7-hadoop260.jar,gs://adw_admin_db_connections/ingestion_jars/avro-tools-1.8.2.jar,gs://adw_admin_db_connections/ingestion_jars/ojdbc7.jar
connect: jdbc:oracle:thin:@mzptest1-scan.aaacorp.com:1521/istmzp.aaamidatlantic.com
username: GCPREADER
password_file: gs://adw_admin_db_connections/source_db_account_credentials/mzp/dev/mzp_ro_user_pw.txt