INSERT INTO adw.dim_vendor (
    vendor_adw_key,
	business_line_adw_key,
	address_adw_key,
	email_adw_key,
	vendor_code,
	vendor_name,
	vendor_type,
	internal_facility_code,
	vendor_contact,
	preferred_vendor,
	vendor_status,
	service_region,
	service_region_description,
	fleet_indicator,
	aaa_facility,
	effective_start_datetime,
	effective_end_datetime,
	active_indicator,
	adw_row_hash,
	integrate_insert_datetime,
	integrate_insert_batch_number,
	integrate_update_datetime,
	integrate_update_batch_number     
)
VALUES ( '6e3dfbd4-2ce0-41a1-ade9-6407d1c2fe52',
    '33b05324-9a68-4775-9c89-eee81867b23d' ,
    '-1',
    '-1',
    'ACA' ,
    'AAA Club Alliance',
    'Membership' ,
    null,
    '',
    '',
    'Active',
    '',
    '',
    '',
    '',
    '2010-01-01',
    '9999-12-01',
    'Y',
    '',
    CURRENT_DATETIME,
    -1,
    CURRENT_DATETIME,
    -1   ) 