CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw_pii.dim_employee`(
    emp_adw_key                       String    NOT NULL,
    active_directory_email_adw_key    String       NOT NULL,
    email_adw_key                     String       NOT NULL,
    phone_adw_key                     String       NOT NULL,
    fax_phone_adw_key                 String       NOT NULL,
    nm_adw_key                        String       NOT NULL,
    emp_typ_cd                        String     ,
    emp_active_directory_user_id     String   ,
    emp_hr_id                        String    ,
    emp_hr_hire_dt                    date            ,
    emp_hr_term_dt                    date            ,
    emp_hr_term_reason                String    ,
    emp_hr_status                     String    ,
    emp_hr_region                     String    ,
    emp_loc_hr                        String    ,
    emp_hr_title                      String    ,
    emp_hr_sprvsr                     String    ,
    emp_hr_job_cd                     String     ,
    emp_hr_cost_center                String    ,
    emp_hr_position_typ               String    ,
    effective_start_datetime          datetime        NOT NULL,
    effective_end_datetime            datetime        NOT NULL,
    actv_ind                          String        NOT NULL,
    adw_row_hash                      String       ,
    integrate_insert_datetime         datetime        NOT NULL,
    integrate_insert_batch_number     int64             NOT NULL,
    integrate_update_datetime         datetime        NOT NULL,
    integrate_update_batch_number        int64             NOT NULL
)
 ;