CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw_pii.dim_address`(
    address_adw_key                  String        NOT NULL,
    raw_address_1_nm                 String     ,
    raw_address_2_nm                 String     ,
    raw_care_of_nm                   String     ,
    raw_city_nm                      String     ,
    raw_state_cd                     String         ,
    raw_postal_cd                    String      ,
    raw_postal_plus_4_cd             String     ,
    raw_country_nm                   String      ,
    cleansed_address_1_nm            String     ,
    cleansed_address_2_nm            String     ,
    cleansed_care_of_nm              String     ,
    cleansed_city_nm                 String     ,
    cleansed_state_cd                String         ,
    cleansed_state_nm                String     ,
    cleansed_postal_cd               String      ,
    cleansed_postal_plus_4_cd        String      ,
    cleansed_country_nm              String      ,
    latitude_nbr                     Numeric   ,
    longitude_nbr                    Numeric   ,
    county_nm                        String     ,
    county_fips                      String     ,
    tm_zone_nm                       String     ,
    address_typ_cd                   String     ,
    address_valid_status_cd          String     ,
    address_valid_typ                String     ,
    integrate_insert_datetime        datetime         NOT NULL,
    integrate_insert_batch_number    int64              NOT NULL,
    integrate_update_datetime        datetime         NOT NULL,
    integrate_update_batch_number    int64              NOT NULL
)
 ;
