INSERT INTO `{{ var.value.INGESTION_PROJECT }}.admin.adw_record_count_validation`
  (data_layer, source_system, table_name, count_type, record_count, adw_insert_datetime, adw_insert_batch_number)
--SELECT 'ingest', '{{ var.value.INGESTION_PROJECT }}', table_id as table_name, 'table_count', row_count as record_count, CURRENT_DATETIME, {{ dag_run.id }} FROM `{{ var.value.INGESTION_PROJECT }}.mzp.__TABLES__`
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_CODE_TYPE', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_code_type` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_CODES', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_codes` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_IUSERS', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_iusers` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_AUTORENEWAL_CARD', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.autorenewal_card` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BATCH_HEADER', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.batch_header` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BATCH_PAYMENT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.batch_payment` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BILL_DETAIL', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.bill_detail` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BILL_SUMMARY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.bill_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BRANCH', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.branch` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_CLUB', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.club` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DAILY_COUNTS_SUMMARY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.daily_counts_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DISCOUNT_HISTORY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.discount_history` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DIVISION', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.division` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_GL_ACCOUNT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.gl_account` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_JOURNAL_ENTRY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.journal_entry` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_CODE', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_code` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_COMMENT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_comment` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_CROSSREF', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_crossref` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER_CODE', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member_code` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER_CROSSREF', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member_crossref` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_FEES', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_fees` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_DETAIL', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_detail` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_PLAN', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_plan` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_SUMMARY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RENEWAL_METHOD_AUDIT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.renewal_method_audit` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RETENTION', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.retention` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RETENTION_OPTION', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.retention_option` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RIDER', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.rider` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SALES_AGENT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.sales_agent` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SALES_AGENT_ACTIVITY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.sales_agent_activity` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SEGMENTATION_HISTORY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.segmentation_history` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SEGMENTATION_SETUP', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.segmentation_setup` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SOLICITATION', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.solicitation` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SOLICITATION_DISCOUNT', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.solicitation_discount` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_TERRITORY', 'table_count', count(*), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.territory`

union all

Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_CODE_TYPE', 'distinct_table_count', count(distinct code_type), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_code_type` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_CODES', 'distinct_table_count', count(distinct code_ky), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_codes` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'CX_IUSERS', 'distinct_table_count', count(distinct user_id), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.cx_iusers` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_AUTORENEWAL_CARD', 'distinct_table_count', count(distinct AUTORENEWAL_CARD_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.autorenewal_card` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BATCH_HEADER', 'distinct_table_count', count(distinct BATCH_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.batch_header` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BATCH_PAYMENT', 'distinct_table_count', count(distinct BATCH_PAYMENT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.batch_payment` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BILL_DETAIL', 'distinct_table_count', count(distinct BILL_DETAIL_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.bill_detail` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BILL_SUMMARY', 'distinct_table_count', count(distinct BILL_SUMMARY_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.bill_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_BRANCH', 'distinct_table_count', count(distinct BRANCH_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.branch` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_CLUB', 'distinct_table_count', count(distinct CLUB_CD), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.club` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DAILY_COUNTS_SUMMARY', 'distinct_table_count', count(distinct DAILY_COUNTS_SUMMARY_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.daily_counts_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DISCOUNT_HISTORY', 'distinct_table_count', count(distinct DISCOUNT_HISTORY_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.discount_history` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_DIVISION', 'distinct_table_count', count(distinct DIVISION_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.division` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_GL_ACCOUNT', 'distinct_table_count', count(distinct GL_ACCOUNT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.gl_account` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_JOURNAL_ENTRY', 'distinct_table_count', count(distinct JOURNAL_ENTRY_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.journal_entry` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER', 'distinct_table_count', count(distinct MEMBER_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_CODE', 'distinct_table_count', count(distinct CONCAT (MEMBERSHIP_KY, CODE)), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_code` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_COMMENT', 'distinct_table_count', count(distinct MEMBERSHIP_COMMENT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_comment` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_CROSSREF', 'distinct_table_count', count(distinct CROSSREFKY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_crossref` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER_CODE', 'distinct_table_count', count(distinct CONCAT (MEMBER_KY, CODE)), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member_code` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBER_CROSSREF', 'distinct_table_count', count(distinct CROSSREFKY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.member_crossref` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP', 'distinct_table_count', count(distinct MEMBERSHIP_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_MEMBERSHIP_FEES', 'distinct_table_count', count(distinct MEMBERSHIP_FEES_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.membership_fees` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_DETAIL', 'distinct_table_count', count(distinct PAYMENT_DETAIL_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_detail` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_PLAN', 'distinct_table_count', count(distinct PAYMENT_PLAN_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_plan` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_PAYMENT_SUMMARY', 'distinct_table_count', count(distinct MEMBERSHIP_PAYMENT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.payment_summary` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RENEWAL_METHOD_AUDIT', 'distinct_table_count', count(distinct RENEWAL_METHOD_AUDIT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.renewal_method_audit` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RETENTION', 'distinct_table_count', count(distinct RETENTION_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.retention` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RETENTION_OPTION', 'distinct_table_count', count(distinct OPTION_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.retention_option` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_RIDER', 'distinct_table_count', count(distinct RIDER_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.rider` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SALES_AGENT', 'distinct_table_count', count(distinct AGENT_ID), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.sales_agent` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SALES_AGENT_ACTIVITY', 'distinct_table_count', count(distinct SALES_AGENT_ACTIVITY_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.sales_agent_activity` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SEGMENTATION_HISTORY', 'distinct_table_count', count(distinct segmentation_history_ky), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.segmentation_history` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SEGMENTATION_SETUP', 'distinct_table_count', count(distinct segmentation_setup_ky), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.segmentation_setup` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SOLICITATION', 'distinct_table_count', count(distinct SOLICITATION_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.solicitation` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_SOLICITATION_DISCOUNT', 'distinct_table_count', count(distinct SOLICITATION_DSCNT_KY), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.solicitation_discount` union all
Select 'ingest', '{{ var.value.INGESTION_PROJECT }}', 'MZ_TERRITORY', 'distinct_table_count', count(distinct CONCAT (BRANCH_KY, ZIP)), CURRENT_DATETIME, {{ dag_run.id }} from `{{ var.value.INGESTION_PROJECT }}.mzp.territory`