INSERT INTO
  `{{var.value.INTEGRATION_PROJECT}}.adw.dim_aca_office`
  (
      aca_office_adw_key,
      aca_office_address,
      aca_office_state_cd,
      aca_office_phone_nbr,
      aca_office_list_source_key,
      aca_office_nm,
      aca_office_status,
      aca_office_typ,
      mbrs_branch_cd,
      ins_department_cd,
      rs_asstc_communicator_center,
      car_care_loc_nbr,
      tvl_branch_cd,
      aca_office_division,
      retail_sales_office_cd,
      retail_manager,
      retail_mngr_email,
      retail_assistant_manager,
      retail_assistant_mngr_email,
      staff_assistant,
      staff_assistant_email,
      car_care_manager,
      car_care_mngr_email,
      car_care_assistant_manager,
      car_care_assistant_mngr_email,
      region_tvl_sales_mgr,
      region_tvl_sales_mgr_email,
      retail_sales_coach,
      retail_sales_coach_email,
      xactly_retail_store_nbr,
      xactly_car_care_store_nbr,
      region,
      car_care_general_manager,
      car_care_general_mngr_email,
      car_care_dirctr,
      car_care_dirctr_email,
      car_care_district_nbr,
      car_care_cost_center_nbr,
      tire_cost_center_nbr,
      admin_cost_center_nbr,
      occupancy_cost_center_nbr,
      retail_general_manager,
      retail_general_mngr_email,
      district_manager,
      district_mngr_email,
      retail_district_nbr,
      retail_cost_center_nbr,
      tvl_cost_center_nbr,
      mbrs_cost_center_nbr,
      facility_cost_center_nbr,
      national_ats_nbr,
      mbrs_division_ky,
      mbrs_division_nm,
      effective_start_datetime,
      effective_end_datetime,
      actv_ind,
      adw_row_hash,
      integrate_insert_datetime,
      integrate_insert_batch_number,
      integrate_update_datetime,
      integrate_update_batch_number
  )
SELECT
  GENERATE_UUID() AS aca_office_adw_key,
  NULL AS aca_office_address,
  NULL AS aca_office_state_cd,
  NULL AS aca_office_phone_nbr,
  '-2' AS aca_office_list_source_key,
  'Enterprise Level Office' aca_office_nm,
  NULL AS aca_office_status,
  NULL AS aca_office_typ,
  NULL AS mbrs_branch_cd,
  NULL AS ins_department_cd,
  NULL AS rs_asstc_communicator_center,
  NULL AS car_care_loc_nbr,
  NULL AS tvl_branch_cd,
  NULL AS aca_office_division,
  NULL AS retail_sales_office_cd,
  NULL AS retail_manager,
  NULL AS retail_mngr_email,
  NULL AS retail_assistant_manager,
  NULL AS retail_assistant_mngr_email,
  NULL AS staff_assistant,
  NULL AS staff_assistant_email,
  NULL AS car_care_manager,
  NULL AS car_care_mngr_email,
  NULL AS car_care_assistant_manager,
  NULL AS car_care_assistant_mngr_email,
  NULL AS region_tvl_sales_mgr,
  NULL AS region_tvl_sales_mgr_email,
  NULL AS retail_sales_coach,
  NULL AS retail_sales_coach_email,
  NULL AS xactly_retail_store_nbr,
  NULL AS xactly_car_care_store_nbr,
  NULL AS region,
  NULL AS car_care_general_manager,
  NULL AS car_care_general_mngr_email,
  NULL AS car_care_dirctr,
  NULL AS car_care_dirctr_email,
  NULL AS car_care_district_nbr,
  NULL AS car_care_cost_center_nbr,
  NULL AS tire_cost_center_nbr,
  NULL AS admin_cost_center_nbr,
  NULL AS occupancy_cost_center_nbr,
  NULL AS retail_general_manager,
  NULL AS retail_general_mngr_email,
  NULL AS district_manager,
  NULL AS district_mngr_email,
  NULL AS retail_district_nbr,
  NULL AS retail_cost_center_nbr,
  NULL AS tvl_cost_center_nbr,
  NULL AS mbrs_cost_center_nbr,
  NULL AS facility_cost_center_nbr,
  NULL AS national_ats_nbr,
  NULL AS mbrs_division_ky,
  NULL AS mbrs_division_nm,
  CAST('1900-01-01' as DATETIME) AS effective_start_datetime,
  CAST('9999-12-31' as DATETIME) AS effective_end_datetime,
  'Y' AS actv_ind,
  '' AS adw_row_hash,
  CURRENT_DATETIME AS integrate_insert_datetime,
  {{ dag_run.id }} as integrate_insert_batch_number,
  CURRENT_DATETIME AS integrate_update_datetime,
  {{ dag_run.id }} as integrate_update_batch_number
FROM (
  SELECT
    1) a
WHERE
  0 = (
  SELECT
    COUNT(aca_office_adw_key)
  FROM
    `{{var.value.INTEGRATION_PROJECT}}.adw.dim_aca_office`
  WHERE aca_office_list_source_key = '-2'
    );
