CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_membership`(
    mbrs_adw_key                     String     NOT NULL,
    address_adw_key                  String        NOT NULL,
    phone_adw_key                    String        NOT NULL,
    product_adw_key                  String     NOT NULL,
    aca_office_adw_key               String     NOT NULL,
    mbrs_source_system_key           int64              ,
    mbrs_id                         String     ,
    mbrs_status_cd                   String      ,
    mbrs_billing_cd                  String      ,
    mbrs_status_dtm                  datetime         ,
    mbrs_cancel_dt                   date             ,
    mbrs_billing_category_cd         String      ,
    mbrs_dues_cost_amt               Numeric   ,
    mbrs_dues_adj_amt                Numeric   ,
    mbrs_future_cancel_ind          String      ,
    mbrs_future_cancel_dt            date             ,
    mbrs_out_of_territory_cd         String      ,
    mbrs_address_change_dtm          datetime         ,
    mbrs_cdx_export_update_dtm       datetime         ,
    mbrs_tier_key                    float64            ,
    mbrs_temporary_address_ind      String      ,
    previous_club_mbrs_id           String     ,
    previous_club_cd                 String      ,
    mbrs_transfer_club_cd            String      ,
    mbrs_transfer_dtm                datetime         ,
    mbrs_merged_previous_club_cd     String      ,
    mbrs_mbrs_merged_previous_id    String     ,
    mbrs_mbrs_merged_previous_key    int64              ,
    mbrs_dn_solicit_ind             String      ,
    mbrs_bad_address_ind            String      ,
    mbrs_dn_send_pubs_ind           String      ,
    mbrs_market_tracking_cd          String      ,
    mbrs_salvage_ind                  String      ,
    mbrs_salvaged_ind               String      ,
    mbrs_dn_salvage_ind             String      ,
    mbrs_group_cd                    String      ,
    mbrs_typ_cd                      String      ,
    mbrs_ebill_ind                  String      ,
    mbrs_marketing_segmntn_cd        String     ,
    mbrs_promo_cd                    String      ,
    mbrs_phone_typ_cd                String      ,
    mbrs_ers_abuser_ind             String      ,
    mbrs_shadow_mcycle_ind          String      ,
    mbrs_student_ind                String      ,
    mbrs_address_ncoa_update_ind    String      ,
    mbrs_assigned_retention_ind     String      ,
    mbrs_mbrs_no_promotion_ind      String      ,
    mbrs_dn_offer_plus_ind          String      ,
    mbrs_aaawld_online_ed_ind       String      ,
    mbrs_shadowrv_coverage_ind      String      ,
    mbrs_heavy_ers_ind              String      ,
    mbrs_purge_ind                  String      ,
    mbrs_unapplied_amt              numeric,
    mbrs_advance_payment_amt        numeric,
    mbrs_balance_amt                numeric,
    payment_plan_future_cancel_dt   date,
    payment_plan_future_cancel_ind   String,
    switch_prim_ind                  String,
    supress_bill_ind                 String,
    offer_end_dt                     date,
    old_payment_plan_ind             String,
    carry_over_amt                   numeric,
    effective_start_datetime         datetime         NOT NULL,
    effective_end_datetime           datetime         NOT NULL,
    actv_ind                         String         NOT NULL,
    adw_row_hash                     String        NOT NULL,
    integrate_insert_datetime        datetime         NOT NULL,
    integrate_insert_batch_number    int64              NOT NULL,
    integrate_update_datetime        datetime         NOT NULL,
    integrate_update_batch_number    int64              NOT NULL
)
 ;