CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_member`(
    mbr_adw_key                       String   NOT NULL,
    mbrs_adw_key                      String   NOT NULL,
    contact_adw_key                   String      NOT NULL,
    mbrs_solicit_adw_key              String   NOT NULL,
    emp_role_adw_key                  String   NOT NULL,
    mbr_source_system_key             int64            ,
    mbrs_id                          String   ,
    mbr_assoc_id                     String    ,
    mbr_ck_dgt_nbr                    int64            ,
    mbr_status_cd                     String    ,
    mbr_extended_status_cd            String    ,
    mbr_expiration_dt                 date           ,
    mbr_card_expiration_dt            date           ,
    prim_mbr_cd               String    ,
    mbr_do_not_renew_ind             String    ,
    mbr_billing_cd                    String    ,
    mbr_billing_category_cd           String    ,
    mbr_status_dtm                    datetime       ,
    mbr_cancel_dt                     date           ,
    mbr_join_aaa_dt                   date           ,
    mbr_join_club_dt                  date           ,
    mbr_reason_joined_cd              String    ,
    mbr_assoc_relation_cd             String    ,
    mbr_solicit_cd                    String   ,
    mbr_source_of_sale_cd             String    ,
    mbr_comm_cd                       String    ,
    mbr_future_cancel_ind            String    ,
    mbr_future_cancel_dt              date           ,
    mbr_renew_method_cd               String    ,
    free_mbr_ind                     String    ,
    previous_club_mbrs_id            String   ,
    previous_club_cd                  String    ,
    mbr_merged_previous_key           int64            ,
    mbr_merged_previous_club_cd       String    ,
    mbr_mbrs_merged_previous_id      String   ,
    mbr_assoc_merged_previous_id     String    ,
    mbr_merged_previous_ck_dgt_nbr    String    ,
    mbr_merged_previous_mbr16_id     String   ,
    mbr_change_nm_dtm                 datetime       ,
    mbr_email_changed_dtm             datetime       ,
    mbr_bad_email_ind                String    ,
    --mbr_email_optout_ind             String    ,
    mbr_web_last_login_dtm            datetime       ,
    mbr_active_expiration_dt          date           ,
    mbr_actvtn_dt                     date           ,
    --mbr_dn_text_ind                  String    ,
    mbr_duplicate_email_ind          String    ,
    --mbr_dn_call_ind                  String    ,
    --mbr_no_email_ind                 String    ,
    --mbr_dn_mail_ind                  String    ,
    mbr_dn_ask_for_email_ind         String    ,
    --mbr_dn_email_ind                 String    ,
    mbr_refused_give_email_ind       String    ,
    mbrs_purge_ind                   String       ,
    payment_plan_future_cancel_dt     date ,
    payment_plan_future_cancel_ind    String ,
    mbr_card_typ_cd                   String       ,
    mbr_card_typ_desc                 String       ,
    entitlement_start_dt              date       ,
    entitlement_end_dt                date       ,
    mbr_previous_expiration_dt        date       ,
    effective_start_datetime          datetime       NOT NULL,
    effective_end_datetime            datetime       NOT NULL,
    actv_ind                          String       NOT NULL,
    adw_row_hash                      String      NOT NULL,
    integrate_insert_datetime         datetime       NOT NULL,
    integrate_insert_batch_number     int64            NOT NULL,
    integrate_update_datetime         datetime       NOT NULL,
    integrate_update_batch_number        int64            NOT NULL
)
 ;
