CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.fact_customer`(
  contact_adw_key                  String   NOT NULL,
    integrate_snapshot_dt            date        NOT NULL,
    active_client_ind               String    ,
    active_email_subscriber_ind     String    ,
    email_opt_out_ind               String    ,
    direct_mail_opt_out_ind         String    ,
    telemarketing_opt_out_ind       String    ,
    latest_email_open_dt             date        ,
    latest_email_click_dt            String   ,
    mbrs_active_donor                String    ,
    mbrs_territory_ind              String    ,
    mbrs_actv_ind                    String    ,
    mbrs_first_dt                    date        ,
    mbrs_last_dt                     date        ,
    mbrs_coverage_level              String   ,
    mbrs_mbr_cnt                     int64         ,
    ins_actv_ind                     String    ,
    ins_lifetime_policy_cnt          int64         ,
    ins_active_policy_cnt            int64         ,
    ins_first_policy_dt              date        ,
    ins_latest_policy_dt             date        ,
    cor_actv_ind                     String    ,
    cor_service_cnt                  int64         ,
    cor_first_service_dt             date        ,
    cor_latest_service_dt            date        ,
    retail_actv_ind                  String    ,
    retail_client_service_cnt        int64         ,
    retail_first_purchase_dt         date        ,
    retail_latest_purchase_dt        date        ,
    tvl_actv_ind                     String    ,
    tvl_booking_cnt                  int64         ,
    tvl_first_booking_dt             date        ,
    tvl_latest_booking_dt            date        ,
    financial_service_actv_ind       String    ,
    financial_service_client_cnt     int64         ,
    financial_service_first_dt       date        ,
    financial_service_latest_dt      date        ,
    actv_ind                         String    NOT NULL,
    adw_row_hash                     String   NOT NULL,
    integrate_insert_datetime        datetime    NOT NULL,
    integrate_insert_batch_number    int64         NOT NULL,
    integrate_update_datetime        datetime    NOT NULL,
    integrate_update_batch_number    int64         NOT NULL
)
 ;