CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.insurance_policy`(
    ins_policy_adw_key               String      NOT null,
    channel_adw_key                  String      NOT null,   
    biz_line_adw_key                 String      NOT null,
    product_category_adw_key         String      NOT null,
    ins_quote_adw_key                String      NOT null,  
    state_adw_key                    String      NOT null,
    emp_adw_key                      String      NOT null,
    ins_policy_system_source_key     int64       NOT null,
    ins_policy_quote_ind             String,         
    ins_policy_number                String,         
    ins_policy_effective_dt          datetime,              
    ins_policy_Expiration_dt         datetime,              
    ins_policy_cntrctd_exp_dt        datetime,              
    ins_policy_annualized_comm       Numeric,   
    ins_policy_annualized_premium    Numeric,   
    ins_policy_billed_comm           Numeric,   
    ins_policy_billed_premium        Numeric,   
    ins_policy_estimated_comm        Numeric,   
    ins_policy_estimated_premium     Numeric,   
    effective_start_datetime         datetime    NOT NULL,
    effective_end_datetime           datetime    NOT NULL,
    actv_ind                         String      NOT null,
    adw_row_hash                     String      NOT null,
    integrate_insert_datetime        datetime    NOT null,
    integrate_insert_batch_number    int64       NOT null,
    integrate_update_datetime        datetime    NOT null,
    integrate_update_batch_number    int64       NOT NULL
) ;