CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.insurance_policy_line`(
    ins_line_adw_key                 String      NOT null,
    ofc_aca_adw_key                  String      NOT null,
    premium_paid_vendor_key          String      NOT null,
    legal_issuing_vendor_key         String      NOT null,
    product_adw_key                  String      NOT null,
    ins_policy_adw_key               String      NOT null,
    ins_policy_line_source_key       int64,               
    ins_line_comm_percent            Numeric,   
    ins_line_delivery_method_cd      String,         
    ins_line_delivery_method_desc    String,         
    ins_line_effective_dt            datetime,             
    ins_line_Expiration_dt           datetime,              
    ins_line_first_written_dt        datetime,              
    ins_line_status                  String,         
    effective_start_datetime         datetime   NOT NULL,
    effective_end_datetime           datetime   NOT NULL,
    actv_ind                         String     NOT null,
    adw_row_hash                     String     NOT null,
    integrate_insert_datetime        datetime   NOT null,
    integrate_insert_batch_number    int64      NOT null,
    integrate_update_datetime        datetime   NOT null,
    integrate_update_batch_number    int64      NOT NULL
) ;