CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.membership_payment_received`(
     mbrs_payment_received_adw_key    String      NOT NULL,
    emp_adw_key                      String      NOT NULL,
    mbrs_adw_key                     String      ,
    mbrs_billing_summary_adw_key     String      NOT NULL,
    mbr_ar_card_adw_key              String      ,
    aca_office_adw_key               String      NOT NULL,
    payment_received_source_key      int64               ,
    payment_received_batch_key       int64               ,
    payment_received_nm              String     ,
    payment_received_cnt             int64               ,
    payment_received_expected_amt    Numeric   ,
    payment_received_created_dtm     datetime          ,
    payment_received_status          String       ,
    payment_received_status_dtm      datetime          ,
    payment_received_amt             Numeric    ,
    payment_received_method_cd       String       ,
    payment_received_method_desc     String      ,
    payment_source_cd                String       ,
    payment_source_desc              String      ,
    payment_typ_cd                   String       ,
    payment_typ_desc                 String      ,
    payment_reason_cd                String       ,
    payment_paid_by_desc             String      ,
    payment_adj_cd                   String       ,
    payment_adj_desc                 String      ,
    payment_received_post_ind         String       ,
    payment_received_post_dtm        datetime          ,
    payment_received_ar_ind           String       ,
    effective_start_datetime         datetime          NOT NULL,
    effective_end_datetime           datetime          NOT NULL,
    actv_ind                         String          NOT NULL,
    adw_row_hash                     String         ,
    integrate_insert_datetime        datetime          NOT NULL,
    integrate_insert_batch_number    int64               NOT NULL,
    integrate_update_datetime        datetime          NOT NULL,
    integrate_update_batch_number    int64               NOT NULL
)
 ;