CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.mbrs_payment_applied_summary`(
    mbrs_payment_apd_summ_adw_key    String      NOT NULL,
    mbrs_payment_apd_rev_adw_key     String      NOT NULL,
    mbrs_adw_key                     String      NOT NULL,
    mbrs_payment_received_adw_key    String      NOT NULL,
    aca_office_adw_key               String      NOT NULL,
    emp_adw_key                      String      NOT NULL,
    payment_applied_source_key       int64               ,
    payment_applied_dt               date              ,
    payment_applied_amt              Numeric   ,
    payment_batch_nm                 String     ,
    payment_method_cd                String       ,
    payment_method_desc              String      ,
    payment_typ_cd                   String       ,
    payment_typ_desc                 String      ,
    payment_adj_cd                   String       ,
    payment_adj_desc                 String      ,
    payment_created_dtm              datetime          ,
    payment_paid_by_cd               String       ,
    payment_unapplied_amt            Numeric    ,
    advance_payment_amt             Numeric,
    payment_source_cd               String,
    payment_source_desc             String,
    payment_tran_typ_cd             String,
    payment_tran_typ_cdesc          String,
    effective_start_datetime         datetime          NOT NULL,
    effective_end_datetime           datetime          NOT NULL,
    actv_ind                         String          NOT NULL,
    adw_row_hash                     String         NOT NULL,
    integrate_insert_datetime        datetime          NOT NULL,
    integrate_insert_batch_number    int64               NOT NULL,
    integrate_update_datetime        datetime          NOT NULL,
    integrate_update_batch_number    int64               NOT NULL
)
 ;
