CREATE TABLE IF NOT EXISTS `{{ var.value.INTEGRATION_PROJECT }}.adw.sales_agent_activity`(
    saa_adw_key                       String     NOT NULL,
    mbr_adw_key                       String     NOT NULL,
    mbrs_adw_key                      String     NOT NULL,
    mbrs_solicit_adw_key              String     NOT NULL,
    aca_sales_office                     String     NOT NULL,
    aca_membership_office_adw_key     String     NOT NULL,
    emp_role_adw_key                  String     NOT NULL,
    product_adw_key                   String     NOT NULL,
    mbrs_payment_apd_dtl_adw_key      String     NOT NULL,
    saa_source_nm                     String     ,
    saa_source_key                    int64              ,
    saa_tran_dt                       date             ,
    mbr_comm_cd                       String      ,
    mbr_comm_desc                     String     ,
    mbr_rider_cd                      String      ,
    mbr_rider_desc                    String     ,
    mbr_expiration_dt                 date             ,
    rider_solicit_cd                  String     ,
    rider_source_of_sale_cd           String      ,
    sales_agent_tran_cd               String     ,
    saa_dues_amt                      Numeric   ,
    saa_daily_billed_ind             String      ,
    rider_billing_category_cd         String     ,
    rider_billing_category_desc       String     ,
    mbr_typ_cd                        String     ,
    saa_commsable_activity_ind         String      ,
    saa_add_on_ind                     String      ,
    saa_ar_ind                         String      ,
    saa_fee_typ_cd                    String      ,
    safety_fund_donation_ind    String      ,
    saa_payment_plan_ind               String      ,
    zip_cd                            String      ,
    saa_daily_cnt_ind                String      ,
    daily_cnt                         int64              ,
    effective_start_datetime          datetime         NOT NULL,
    effective_end_datetime            datetime         NOT NULL,
    actv_ind                          String         NOT NULL,
    adw_row_hash                      String        NOT NULL,
    integrate_insert_datetime         datetime         NOT NULL,
    integrate_insert_batch_number     int64              NOT NULL,
    integrate_update_datetime         datetime         NOT NULL,
    integrate_update_batch_number        int64              NOT NULL
)
 ;