cluster_name        : 'sqoop-gcp-outbound-adw-pii'
num_workers         : '3'
master_machine_type : 'n1-standard-2'
master_disk_type    : 'pd-standard'
master_disk_size    : '20'
worker_machine_type : 'n1-standard-2'
worker_disk_type    : 'pd-standard'
worker_disk_size    : '30'
idle_delete_ttl     : '10800'