CREATE OR REPLACE TABLE
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_office_work_transformed` AS
SELECT
  Address,
  State,
  Phone,
  Code,
  Name,
  Status,
  Officetype,
  mbrs_division_ky,
  mbrs_division_nm,
  MembershipOfficeID,
  InsuranceOfficeID,
  CommCenter,
  CarCareOfficeID,
  TravelOfficeID,
  Division,
  RetailSalesOfficeID,
  RM_Cost_Center_Manager,
  RM_Cost_Center_Manager_Email,
  RAM,
  RAM_Email,
  Staff_Assistant,
  Staff_Assistant_Email,
  Car_Care_Manager_Cost_Center_Manager,
  Care_Care_Manager_Cost_Center_Manager_Email,
  Car_Care_Asst_Manager,
  Car_Care_Asst_Manager_Email,
  RTSM,
  RTSM_Email,
  Retail_Sales_Coach,
  Retail_Sales_Coach_email,
  Xactly_Retail_Store_Number,
  Xactly_Care_Care_Store_Number,
  PresidentRegion,
  GM_Car_Care,
  GM_Car_Care_Email,
  Car_Care_Director,
  Car_Care_Director_email,
  CarCareDistrictNumber,
  CarCareCostCenter,
  TireCostCenter,
  AdminCostCenter,
  OccupancyCostCenter,
  GM_Retail,
  GM_Retail_Email,
  Director_District_Manager,
  Director_District_Manager_Email,
  RetailDistrictNumber,
  RetailSalesCostCenter,
  TravelCostCenter,
  MembershipCostCenter,
  FacilityCostCenter,
  National_ATS_Number,
  dupe_check,
  CURRENT_DATETIME() AS last_upd_dt,
  TO_BASE64(MD5(CONCAT( ifnull(Address,
          ''),'|', ifnull(State,
          ''),'|', ifnull(Phone,
          ''),'|', ifnull(Name,
          ''),'|', ifnull(Status,
          ''),'|', ifnull(Officetype,
          ''),'|', ifnull(mbrs_division_ky,
          ''),'|', ifnull(mbrs_division_nm,
          ''),'|', ifnull(MembershipOfficeID,
          ''),'|', ifnull(InsuranceOfficeID,
          ''),'|', ifnull(CommCenter,
          ''),'|', ifnull(CarCareOfficeID,
          ''),'|', ifnull(TravelOfficeID,
          ''),'|', ifnull(Division,
          ''),'|', ifnull(RetailSalesOfficeID,
          ''),'|', ifnull(RM_Cost_Center_Manager,
          ''),'|', ifnull(RM_Cost_Center_Manager_Email,
          ''),'|', ifnull(RAM,
          ''),'|', ifnull(RAM_Email,
          ''),'|', ifnull(Staff_Assistant,
          ''),'|', ifnull(Staff_Assistant_Email,
          ''),'|', ifnull(Car_Care_Manager_Cost_Center_Manager,
          ''),'|', ifnull(Care_Care_Manager_Cost_Center_Manager_Email,
          ''),'|', ifnull(Car_Care_Asst_Manager,
          ''),'|', ifnull(Car_Care_Asst_Manager_Email,
          ''),'|', ifnull(RTSM,
          ''),'|', ifnull(RTSM_Email,
          ''),'|', ifnull(Retail_Sales_Coach,
          ''),'|', ifnull(Retail_Sales_Coach_email,
          ''),'|', ifnull(Xactly_Retail_Store_Number,
          ''),'|', ifnull(Xactly_Care_Care_Store_Number,
          ''),'|', ifnull(PresidentRegion,
          ''),'|', ifnull(GM_Car_Care,
          ''),'|', ifnull(GM_Car_Care_Email,
          ''),'|', ifnull(Car_Care_Director,
          ''),'|', ifnull(Car_Care_Director_email,
          ''),'|', ifnull(CarCareDistrictNumber,
          ''),'|', ifnull(CarCareCostCenter,
          ''),'|', ifnull(TireCostCenter,
          ''),'|', ifnull(AdminCostCenter,
          ''),'|', ifnull(OccupancyCostCenter,
          ''),'|', ifnull(GM_Retail,
          ''),'|', ifnull(GM_Retail_Email,
          ''),'|', ifnull(Director_District_Manager,
          ''),'|', ifnull(Director_District_Manager_Email,
          ''),'|', ifnull(RetailDistrictNumber,
          ''),'|', ifnull(RetailSalesCostCenter,
          ''),'|', ifnull(TravelCostCenter,
          ''),'|', ifnull(MembershipCostCenter,
          ''),'|', ifnull(FacilityCostCenter,
          ''),'|', ifnull(National_ATS_Number,
          ''),'|' ))) AS adw_row_hash
FROM
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.office_source` AS office
WHERE
  dupe_check =1