CREATE OR REPLACE TABLE
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.office_work_stage` AS
SELECT
  COALESCE(target.aca_office_adw_key,
    GENERATE_UUID()) AS aca_office_adw_key,
  source.Address AS aca_office_address,
  source.State AS aca_office_state_cd,
  source.Phone AS aca_office_phone_nbr,
  source.Code AS aca_office_list_source_key,
  source.Name AS aca_office_nm,
  source.Status AS aca_office_status,
  source.Officetype AS aca_office_typ,
  source.mbrs_division_ky AS mbrs_division_ky,
  source.mbrs_division_nm AS mbrs_division_nm,
  source.MembershipOfficeID AS mbrs_branch_cd,
  source.InsuranceOfficeID AS ins_department_cd,
  source.CommCenter AS rs_asstc_communicator_center,
  source.CarCareOfficeID AS car_care_loc_nbr,
  source.TravelOfficeID AS tvl_branch_cd,
  source.Division AS aca_store_division,
  source.RetailSalesOfficeID AS retail_sales_office_cd,
  source.RM_Cost_Center_Manager AS retail_manager,
  source.RM_Cost_Center_Manager_Email AS retail_mngr_email,
  source.RAM AS retail_assistant_manager,
  source.RAM_Email AS retail_assistant_mngr_email,
  source.Staff_Assistant AS staff_assistant,
  source.Staff_Assistant_Email AS staff_assistant_email,
  source.Car_Care_Manager_Cost_Center_Manager AS car_care_manager,
  source.Care_Care_Manager_Cost_Center_Manager_Email AS car_care_mngr_email,
  source.Car_Care_Asst_Manager AS car_care_assistant_manager,
  source.Car_Care_Asst_Manager_Email AS car_care_assistant_mngr_email,
  source.RTSM AS region_tvl_sales_mgr,
  source.RTSM_Email AS region_tvl_sales_mgr_email,
  source.Retail_Sales_Coach AS retail_sales_coach,
  source.Retail_Sales_Coach_email AS retail_sales_coach_email,
  source.Xactly_Retail_Store_Number AS xactly_retail_store_nbr,
  source.Xactly_Care_Care_Store_Number AS xactly_car_care_store_nbr,
  source.PresidentRegion AS region,
  source.GM_Car_Care AS car_care_general_manager,
  source.GM_Car_Care_Email AS car_care_general_mngr_email,
  source.Car_Care_Director AS car_care_dirctr,
  source.Car_Care_Director_email AS car_care_dirctr_email,
  source.CarCareDistrictNumber AS car_care_district_nbr,
  source.CarCareCostCenter AS car_care_cost_center_nbr,
  source.TireCostCenter AS tire_cost_center_nbr,
  source.AdminCostCenter AS admin_cost_center_nbr,
  source.OccupancyCostCenter AS occupancy_cost_center_nbr,
  source.GM_Retail AS retail_general_manager,
  source.GM_Retail_Email AS retail_general_mngr_email,
  source.Director_District_Manager AS district_manager,
  source.Director_District_Manager_Email AS district_mngr_email,
  source.RetailDistrictNumber AS retail_district_nbr,
  source.RetailSalesCostCenter AS retail_cost_center_nbr,
  source.TravelCostCenter AS tvl_cost_center_nbr,
  source.MembershipCostCenter AS mbrs_cost_center_nbr,
  source.FacilityCostCenter AS facility_cost_center_nbr,
  source.National_ATS_Number AS national_ats_nbr,
  last_upd_dt AS effective_start_datetime,
  CAST('9999-12-31' AS datetime) effective_end_datetime,
  'Y' AS actv_ind,
  source.adw_row_hash,
  CURRENT_DATETIME() integrate_insert_datetime,
  {{ dag_run.id }} integrate_insert_batch_number,
  CURRENT_DATETIME() integrate_update_datetime,
  {{ dag_run.id }} integrate_update_batch_number
FROM
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_office_work_transformed` source
LEFT JOIN
  `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_aca_office` target
ON
  (CAST(source.code AS String)=CAST(target.aca_office_list_source_key AS String)
    AND target.actv_ind='Y')
WHERE
  target.aca_office_adw_key IS NULL
  OR source.adw_row_hash <> target.adw_row_hash
UNION ALL
SELECT
  target.aca_office_adw_key,
  target.aca_office_address,
  target.aca_office_state_cd,
  target.aca_office_phone_nbr,
  target.aca_office_list_source_key,
  target.aca_office_nm,
  target.aca_office_status,
  target.aca_office_typ,
  target.mbrs_division_ky,
  target.mbrs_division_nm,
  target.mbrs_branch_cd,
  target.ins_department_cd,
  target.rs_asstc_communicator_center,
  target.car_care_loc_nbr,
  target.tvl_branch_cd,
  target.aca_office_division,
  target.retail_sales_office_cd,
  target.retail_manager,
  target.retail_mngr_email,
  target.retail_assistant_manager,
  target.retail_assistant_mngr_email,
  target.staff_assistant,
  target.staff_assistant_email,
  target.car_care_manager,
  target.car_care_mngr_email,
  target.car_care_assistant_manager,
  target.car_care_assistant_mngr_email,
  target.region_tvl_sales_mgr,
  target.region_tvl_sales_mgr_email,
  target.retail_sales_coach,
  target.retail_sales_coach_email,
  target.xactly_retail_store_nbr,
  target.xactly_car_care_store_nbr,
  target.region,
  target.car_care_general_manager,
  target.car_care_general_mngr_email,
  target.car_care_dirctr,
  target.car_care_dirctr_email,
  target.car_care_district_nbr,
  target.car_care_cost_center_nbr,
  target.tire_cost_center_nbr,
  target.admin_cost_center_nbr,
  target.occupancy_cost_center_nbr,
  target.retail_general_manager,
  target.retail_general_mngr_email,
  target.district_manager,
  target.district_mngr_email,
  target.retail_district_nbr,
  target.retail_cost_center_nbr,
  target.tvl_cost_center_nbr,
  target.mbrs_cost_center_nbr,
  target.facility_cost_center_nbr,
  target.national_ats_nbr,
  target.effective_start_datetime,
  DATETIME_SUB(source.last_upd_dt,
    INTERVAL 1 SECOND) AS effective_end_datetime,
  'N' AS actv_ind,
  target.adw_row_hash,
  target.integrate_insert_datetime,
  target.integrate_insert_batch_number,
  CURRENT_DATETIME(),
  target.integrate_update_batch_number
FROM
  `{{ var.value.INTEGRATION_PROJECT }}.adw_work.mzp_office_work_transformed` source
JOIN
  `{{ var.value.INTEGRATION_PROJECT }}.adw.dim_aca_office` target
ON
  (CAST(source.code AS String)=CAST(target.aca_office_list_source_key AS String)
    AND target.actv_ind='Y')
WHERE
  source.adw_row_hash <> target.adw_row_hash