jar_files: gs://adw_admin_db_connections/ingestion_jars/sqoop-1.4.7-hadoop260.jar,gs://adw_admin_db_connections/ingestion_jars/avro-tools-1.8.2.jar,gs://adw_admin_db_connections/ingestion_jars/jtds-1.3.1.jar
connect: jdbc:jtds:sqlserver://ACACSDBPROD.corp.ad.aaamidatlantic.com:61318;instance=CONNECT;DOMAIN=aaacorp;useNTLMv2=true;
username: SVCGCPUSER
password_file: gs://adw_admin_db_connections/source_db_account_credentials/pos/prd/pos_ro_user_pw.txt
connection_manager: org.apache.sqoop.manager.SQLServerManager
driver: net.sourceforge.jtds.jdbc.Driver
db_name: Avatar_3_prod