cluster_name        : 'sqoop-gcp-ingest-ersbilling'
num_workers         : '2'
master_machine_type : 'n1-standard-1'
master_disk_type    : 'pd-standard'
master_disk_size    : '200'
worker_machine_type : 'n1-standard-1'
worker_disk_type    : 'pd-standard'
worker_disk_size    : '300'
idle_delete_ttl     : '10800'