jar_files: gs://adw_ingest_utilities/ingestion_jars/sqoop-1.4.7-hadoop260.jar,gs://adw_ingest_utilities/ingestion_jars/avro-tools-1.8.2.jar,gs://adw_ingest_utilities/ingestion_jars/jtds-1.3.1.jar
connect: jdbc:jtds:sqlserver://MTLPCIPRODDB.aaacorp.com:1433;DOMAIN=aaacorp;useNTLMv2=true;databaseName=ChargERS_V2;
username: SVCGCPUSER
password_file: gs://adw_admin_db_connections/source_db_account_credentials/chargers/prd/chargers_ro_user_pw.txt
connection_manager: org.apache.sqoop.manager.SQLServerManager
driver: net.sourceforge.jtds.jdbc.Driver
db_name: ChargERS_V2
